/* hello.c generated by valac 0.14.0, the Vala compiler
 * generated from hello.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




void _vala_main (gchar** args, int args_length1);


void _vala_main (gchar** args, int args_length1) {
	g_print ("Hello World\n");
}


int main (int argc, char ** argv) {
	g_type_init ();
	_vala_main (argv, argc);
	return 0;
}



